function skillsMember() {
    const skills = [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Node.js",
        "Express.js",
        "MongoDB",
        "Python",
        "Django",
        "Flask",
        "Java",
        "Spring",
        "C",
        "C++",
        "C#",
        "PHP",
        "Laravel",
        "Ruby",
        "Ruby on Rails",
        "Swift",
        "Kotlin",
        "Objective-C",
        "SQL",
        "NoSQL",
        "Firebase",
        "AWS",
        "Azure",
        "Google Cloud Platform",
        "Docker",
        "Kubernetes",
        "Jenkins",
        "Git",
        "GitHub",
        "GitLab",
        "Bitbucket",
        "Jira",
        "Confluence",
        "Slack",
        "Trello",
        "Asana",
        "Figma",
        "Sketch",
        "Adobe XD",
        "Photoshop",
        "Illustrator",
        "InDesign",
        "After Effects",
        "Premiere Pro",
        "Final Cut Pro",
        "Blender",
        "Unity",
        "Unreal Engine",
        "3ds Max",
        "Maya",
        "ZBrush",
        "AutoCAD",
        "SolidWorks",
        "Fusion 360",
        "Revit",
        "SketchUp",
        "Rhino",
        "Grasshopper",
        "Arduino",
        "Raspberry Pi",
        "IoT",
        "AI",
        "ML",
        "DL",
        "NLP",
        "CV",
        "Big Data",
        "Blockchain",
        "Cryptocurrency",
        "Cybersecurity",
        "Ethical Hacking",
        "Forensics",
        "Penetration Testing",
        "Incident Response",
        "Risk Management",
        "Compliance",
        "Audit",
        "DevOps",
        "SRE",
        "QA",
        "Testing",
        "Automation",
        "Scrum",
        "Kanban",
        "Lean",
        "Agile",
        "Waterfall",
        "SDLC",
        "TDD",
        "BDD",
        "CI",
        "CD",
        "API",
        "REST",
        "GraphQL",
        "SOAP",
        "OAuth",
        "JWT",
        "S